name: Backend Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "worker/**"
      - ".github/workflows/backend_deploy.yaml"

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: worker/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: worker

      - name: Inject wrangler.toml from secret
        run: |
          cat <<EOF > wrangler.toml
          ${{ secrets.BACKEND_TOML }}
          EOF
        working-directory: worker

      - name: Deploy worker
        run: pnpm run deploy
        working-directory: worker
