name: Frontend Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_deploy.yaml"

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Inject environment secrets
        run: |
          cat <<EOF > .env.production
          ${{ secrets.FRONTEND_ENV }}
          EOF
          cat <<EOF > wrangler.toml
          ${{ secrets.FRONTEND_TOML }}
          EOF
        working-directory: frontend

      - name: Build frontend
        run: pnpm run build
        working-directory: frontend

      - name: Deploy frontend
        run: pnpm run deploy
        working-directory: frontend
